delete from registrations;
delete from training_classes;
delete from lesson_completions;
delete from students;
delete from syllabuses_modules;
delete from syllabuses;
delete from modules_lessons;
delete from modules;
delete from lessons;
